name: CI

# Run the deployment only when code is committed to the branch.
on: pull_request

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
  lint-and-audit:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none
        tools: composer

    - name: Set composer token
      run: composer config github-oauth.github.com ${{ secrets.PRIVATE_ACCESS_TOKEN }} 

    - name: Install dependencies
        run: composer install --prefer-dist --no-suggest --no-progress

    - name: PHPCS check
      if: always()
      uses: chekalsky/phpcs-action@v1
      with:
        phpcs_bin_path: './vendor/bin/phpcs'

    - name: PHP Syntax Errors
      if: always()
      run: if find . -name "*.php" ! -path "./vendor/*" ! -path "./admin/bsf-core/*" -exec php -l {} \; | grep "Errors parsing"; then exit 1; fi